/** All player-visible text. Switching language = swapping this data. */
export const STR = {
  title: "MOBIUS HIVE",
  subtitle: "16-BIT WORLD SIMULATOR",
  start: "PRESS E / TAP / START",
  start_hint: "Arrows / WASD move · E or A talk & act · Q objectives · Esc closes",
  loading: "WAKING THE HIVE…",

  hud_cycle: "CYCLE",
  hud_gi: "GI",
  hud_mic: "MIC",
  hud_realms: "REALMS SEALED",
  hud_event: "EVENT",
  hud_quest: "QUEST",
  hud_demo: "SNAPSHOT",
  hud_live: "LIVE",

  hint_talk: "[E] TALK",
  hint_shard: "[E] TAKE SHARD",
  hint_beacon_locked: "BEACON DORMANT — SWEEP SHARDS FIRST",
  hint_beacon_ready: "[E] LIGHT BEACON",
  hint_beacon_done: "BEACON LIT",
  hint_fountain_locked: "FOUNTAIN LOCKED — SEAL ALL REALMS",
  hint_fountain_ready: "[E] RESTORE THE BEACON",
  hint_explore: "Explore the HIVE — sweep shards, light beacons, lift the fog.",

  shards_label: "SHARDS",
  task_sweep: "Sweep {n} integrity shards from this realm.",
  task_done: "Shards swept. Light the realm beacon.",
  beacon_lit: "{realm} beacon lit. Global Integrity rises.",
  realm_sealed: "{realm} SEALED",

  fountain_unlocked: "The central Fountain stirs. Return to ZEUS at the Forge.",
  win_title: "CYCLE C-344 SEALED",
  win_body: "The Signal Fog recedes. Live continuity is restored across the HIVE.",
  win_jade: "JADE: Bitcoin gave you stone. The HIVE gave you memory.",
  win_again: "[E] WALK THE HIVE AGAIN",

  legend_you: "YOU",
  legend_portal: "PORTAL",

  obj_title: "OBJECTIVES",
  obj_btn: "\u25e7 OBJECTIVES",
  obj_quest: "QUEST: RESTORE THE BEACON",
  obj_step_seal: "Sweep & seal the realms",
  obj_step_fountain: "Restore the Forge Fountain",
  obj_step_fountain_locked: "Restore the Forge Fountain (locked)",
  obj_realms: "REALMS",
  obj_close: "[Q] / TAP \u25e7 TO CLOSE",
  st_new: "not visited",
  st_go: "shards {got}/{total}",
  st_ready: "light beacon",
  st_sealed: "SEALED",
  objective_hint: "Objective: sweep {n} shards in {realm}",
};
